"""Data landscape endpoint — data quality, metadata, and source overview.

Reads the pre-computed analysis from _analysis_results.json (generated by the
analysis script) and enriches with live DB row counts.  Cached with 24h TTL.
"""
import json
import logging
from pathlib import Path

from fastapi import APIRouter, Depends
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from src.dependencies import get_db, get_cache
from src.middleware.auth import get_current_user
from src.services.cache import CacheService

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/data-landscape", tags=["data-landscape"])

# Pre-computed analysis results (generated by the analysis script)
_APP_DIR = Path(__file__).resolve().parents[3]
ANALYSIS_PATH = _APP_DIR / "_analysis_results.json"
if not ANALYSIS_PATH.exists():
    ANALYSIS_PATH = Path("/app/_analysis_results.json")

CACHE_TTL = 86400  # 24 hours


def _load_analysis() -> dict | None:
    """Load the pre-computed analysis JSON.  Returns None if missing."""
    if not ANALYSIS_PATH.exists():
        return None
    try:
        with open(ANALYSIS_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as exc:
        logger.warning("data_landscape: failed to load analysis JSON: %s", exc)
        return None


async def _get_db_table_counts(db: AsyncSession) -> list[dict]:
    """Query live row counts for key tables."""
    tables = [
        ("dim_occupation", "ESCO occupations"),
        ("dim_skill", "ESCO skills"),
        ("dim_region", "UAE regions/emirates"),
        ("dim_sector", "ISIC sectors"),
        ("dim_institution", "Higher education institutions"),
        ("fact_demand_vacancies_agg", "LinkedIn job postings"),
        ("fact_supply_talent_agg", "FCSC + Bayanat workforce"),
        ("fact_ai_exposure_occupation", "AI exposure scores"),
        ("fact_occupation_skills", "Occupation-skill mappings"),
        ("crosswalk_soc_isco", "SOC-ISCO crosswalk"),
    ]
    results = []
    for table, description in tables:
        try:
            count = (await db.execute(text(f"SELECT count(*) FROM {table}"))).scalar() or 0
            results.append({"table": table, "rows": count, "description": description})
        except Exception:
            results.append({"table": table, "rows": 0, "description": description})
    return results


async def _get_view_counts(db: AsyncSession) -> list[dict]:
    """Query live row counts for materialized views."""
    views = [
        ("vw_supply_talent", "Supply: talent by time/region/occupation"),
        ("vw_demand_jobs", "Demand: jobs by time/region/occupation"),
        ("vw_ai_impact", "AI exposure scores by occupation"),
        ("vw_gap_cube", "Supply-demand gap analysis"),
        ("vw_forecast_demand", "Forecast predictions"),
    ]
    results = []
    for view, description in views:
        try:
            count = (await db.execute(text(f"SELECT count(*) FROM {view}"))).scalar() or 0
            results.append({"view": view, "rows": count, "description": description})
        except Exception:
            results.append({"view": view, "rows": 0, "description": description})
    return results


def _build_sources(analysis: dict) -> list[dict]:
    """Build the data sources list from the analysis JSON."""
    sources = []

    # 1. LinkedIn Job Postings
    demand = analysis.get("demand", {})
    sources.append({
        "name": "LinkedIn Job Postings",
        "category": "demand",
        "files": 1,
        "rows": demand.get("total_postings", 0),
        "time_start": demand.get("date_range", {}).get("min", "")[:7] if demand.get("date_range") else "",
        "time_end": demand.get("date_range", {}).get("max", "")[:7] if demand.get("date_range") else "",
        "completeness": round(100 - demand.get("missing_date_pct", 0), 1),
        "status": "active",
    })

    # 2. FCSC Employment
    supply = analysis.get("supply", {})
    fcsc_emp = supply.get("fcsc_employment", {})
    sources.append({
        "name": "FCSC Employment Survey",
        "category": "supply",
        "files": 1,
        "rows": fcsc_emp.get("rows", 0),
        "time_start": fcsc_emp.get("years", [""])[0] if fcsc_emp.get("years") else "",
        "time_end": fcsc_emp.get("years", [""])[-1] if fcsc_emp.get("years") else "",
        "completeness": 95.0,
        "status": "active",
    })

    # 3. FCSC Labour Force
    fcsc_lf = supply.get("fcsc_labour_force", {})
    sources.append({
        "name": "FCSC Labour Force Survey",
        "category": "supply",
        "files": 1,
        "rows": fcsc_lf.get("rows", 0),
        "time_start": fcsc_lf.get("years", [""])[0] if fcsc_lf.get("years") else "",
        "time_end": fcsc_lf.get("years", [""])[-1] if fcsc_lf.get("years") else "",
        "completeness": 95.0,
        "status": "active",
    })

    # 4. FCSC Unemployment
    fcsc_un = supply.get("fcsc_unemployment", {})
    sources.append({
        "name": "FCSC Unemployment Survey",
        "category": "supply",
        "files": 1,
        "rows": fcsc_un.get("rows", 0),
        "time_start": fcsc_un.get("years", [""])[0] if fcsc_un.get("years") else "",
        "time_end": fcsc_un.get("years", [""])[-1] if fcsc_un.get("years") else "",
        "completeness": 95.0,
        "status": "active",
    })

    # 5. MOHRE KPIs
    sources.append({
        "name": "MOHRE KPI Tracker",
        "category": "supply",
        "files": 1,
        "rows": 28,
        "time_start": "2020",
        "time_end": "2024",
        "completeness": 100.0,
        "status": "active",
    })

    # 6. Bayanat Employment
    bayanat = supply.get("bayanat", {})
    sources.append({
        "name": "Bayanat Employment",
        "category": "supply",
        "files": bayanat.get("total_files", 0),
        "rows": bayanat.get("total_rows", 0),
        "time_start": analysis.get("temporal", {}).get("bayanat_employment", {}).get("start", ""),
        "time_end": analysis.get("temporal", {}).get("bayanat_employment", {}).get("end", ""),
        "completeness": 90.0,
        "status": "active",
    })

    # 7. ESCO Taxonomy
    skills = analysis.get("skills", {}).get("esco", {})
    esco_rows = skills.get("occupations", 0) + skills.get("skills", 0) + skills.get("mappings", 0)
    sources.append({
        "name": "ESCO Taxonomy",
        "category": "taxonomy",
        "files": 6,
        "rows": esco_rows,
        "time_start": "2024",
        "time_end": "2024",
        "completeness": 98.0,
        "status": "active",
    })

    # 8. O*NET Taxonomy
    onet = analysis.get("skills", {}).get("onet", {})
    onet_rows = sum(onet.get(k, 0) for k in (
        "skill_records", "knowledge_records", "technology_records",
        "alternate_titles", "task_statements", "emerging_tasks",
    ))
    sources.append({
        "name": "O*NET v30.2",
        "category": "taxonomy",
        "files": 7,
        "rows": onet_rows,
        "time_start": "2026",
        "time_end": "2026",
        "completeness": 99.0,
        "status": "active",
    })

    # 9. AIOE Scores
    ai = analysis.get("ai_impact", {})
    sources.append({
        "name": "AI Occupational Exposure",
        "category": "ai_impact",
        "files": 2,
        "rows": ai.get("total_occupations", 0),
        "time_start": "2024",
        "time_end": "2024",
        "completeness": 100.0,
        "status": "active",
    })

    # 10. BLS Crosswalk
    sources.append({
        "name": "BLS ISCO-SOC Crosswalk",
        "category": "crosswalk",
        "files": 1,
        "rows": 1100,
        "time_start": "2010",
        "time_end": "2010",
        "completeness": 100.0,
        "status": "active",
    })

    # 11. Education — Bayanat
    edu = analysis.get("education", {})
    edu_bay = edu.get("bayanat", {})
    sources.append({
        "name": "Bayanat Education",
        "category": "education",
        "files": edu_bay.get("files", 0),
        "rows": edu_bay.get("rows", 0),
        "time_start": analysis.get("temporal", {}).get("bayanat_education", {}).get("start", ""),
        "time_end": analysis.get("temporal", {}).get("bayanat_education", {}).get("end", ""),
        "completeness": 85.0,
        "status": "active",
    })

    # 12. HE Institutions
    inst = edu.get("institutions", {})
    sources.append({
        "name": "UAE HE Institutions",
        "category": "education",
        "files": 1,
        "rows": inst.get("total", 0),
        "time_start": "2024",
        "time_end": "2024",
        "completeness": 100.0,
        "status": "active",
    })

    # 13. SCAD Abu Dhabi
    scad = analysis.get("geographic", {}).get("scad_abu_dhabi", {})
    sources.append({
        "name": "SCAD Abu Dhabi",
        "category": "geographic",
        "files": scad.get("files", 0),
        "rows": scad.get("rows", 0),
        "time_start": analysis.get("temporal", {}).get("scad_abu_dhabi", {}).get("start", ""),
        "time_end": analysis.get("temporal", {}).get("scad_abu_dhabi", {}).get("end", ""),
        "completeness": 80.0,
        "status": "active",
    })

    return sources


def _build_emiratisation(analysis: dict) -> dict:
    """Extract Emiratisation data from the MOHRE KPIs."""
    mohre = analysis.get("supply", {}).get("mohre_kpis", {})

    emirati_data = mohre.get("emiratis_in_private_sector", {})
    emiratis = []
    for year, val in zip(emirati_data.get("years", []), emirati_data.get("values", [])):
        emiratis.append({"year": year, "value": int(val)})

    nafis_data = mohre.get("nafis_establishments_hiring_emiratis", {})
    nafis = []
    for year, val in zip(nafis_data.get("years", []), nafis_data.get("values", [])):
        nafis.append({"year": year, "value": int(val)})

    return {
        "emiratis_in_private_sector": emiratis,
        "nafis_establishments": nafis,
        "growth_pct": emirati_data.get("growth", 0),
    }


def _build_geographic_coverage() -> dict:
    """Static geographic coverage map (which data sources cover each emirate)."""
    return {
        "Dubai": ["linkedin", "bayanat", "education", "institutions"],
        "Abu Dhabi": ["linkedin", "bayanat", "education", "institutions", "scad"],
        "Sharjah": ["linkedin", "bayanat", "education", "institutions"],
        "Ajman": ["linkedin", "bayanat", "education", "institutions"],
        "Ras Al Khaimah": ["linkedin", "bayanat", "education", "institutions"],
        "Fujairah": ["linkedin", "bayanat", "education", "institutions"],
        "Umm Al Quwain": ["bayanat", "institutions"],
    }


def _build_data_quality(analysis: dict) -> dict:
    """Build data quality summary from the analysis JSON."""
    quality = analysis.get("quality", {})
    return {
        "gaps": quality.get("data_gaps", []),
        "strengths": quality.get("strengths", []),
    }


def _build_education_pipeline(analysis: dict) -> dict:
    """Build education pipeline summary."""
    edu = analysis.get("education", {})
    inst = edu.get("institutions", {})
    programs = edu.get("programs", {})
    courses = edu.get("courses", {})
    tech = edu.get("tech_courses", {})

    # Clean up institution-by-emirate (collapse multi-emirate keys)
    raw_by_emirate = inst.get("by_emirate", {})
    by_emirate = {}
    for key, val in raw_by_emirate.items():
        # Take the first emirate if it's a comma-separated list
        primary = key.split(",")[0].strip()
        by_emirate[primary] = by_emirate.get(primary, 0) + val

    return {
        "institutions": inst.get("total", 0),
        "programs": programs.get("total", 0),
        "courses": courses.get("total", 0),
        "tech_courses": tech,
        "degree_distribution": programs.get("degree_distribution", {}),
        "institutions_by_emirate": by_emirate,
    }


def _build_ai_impact_summary(analysis: dict) -> dict:
    """Build AI impact summary."""
    ai = analysis.get("ai_impact", {})
    risk = ai.get("risk_distribution", {})
    high_risk_pct = 0
    total_assessed = ai.get("total_occupations", 0)
    if total_assessed > 0:
        high_count = risk.get("Very High", 0) + risk.get("High", 0)
        high_risk_pct = round(high_count / total_assessed * 100, 1)

    return {
        "total_assessed": total_assessed,
        "risk_distribution": risk,
        "high_risk_pct": high_risk_pct,
        "top_exposed": [item["title"] for item in ai.get("top5_exposed", [])],
        "top_safe": [item["title"] for item in ai.get("top5_safe", [])],
    }


def _build_skills_taxonomy(analysis: dict) -> dict:
    """Build skills taxonomy summary."""
    skills = analysis.get("skills", {})
    esco = skills.get("esco", {})
    onet = skills.get("onet", {})
    top_essential_raw = skills.get("top_essential", {})

    top_essential = [
        {"skill": skill, "occupations": count}
        for skill, count in list(top_essential_raw.items())[:10]
    ]

    return {
        "esco_occupations": esco.get("occupations", 0),
        "esco_skills": esco.get("skills", 0),
        "esco_mappings": esco.get("mappings", 0),
        "essential_skills": esco.get("essential", 0),
        "optional_skills": esco.get("optional", 0),
        "onet_occupations": onet.get("occupations", 0),
        "onet_skill_records": onet.get("skill_records", 0),
        "onet_hot_technologies": onet.get("hot_technologies", 0),
        "onet_emerging_tasks": onet.get("emerging_tasks", 0),
        "top_essential_skills": top_essential,
    }


@router.get("")
async def get_data_landscape(
    user=Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
    cache: CacheService = Depends(get_cache),
):
    """Return comprehensive data landscape overview.

    Combines pre-computed analysis from _analysis_results.json with live
    DB row counts.  Result is cached in Redis for 24 hours.
    """
    cache_key = CacheService.make_key("data_landscape")
    cached = await cache.get(cache_key)
    if cached:
        logger.debug("data_landscape: returning cached result")
        return cached

    analysis = _load_analysis()
    if analysis is None:
        logger.warning("data_landscape: analysis JSON not found at %s", ANALYSIS_PATH)
        return {"error": f"Analysis results not found at {ANALYSIS_PATH}"}

    # Live DB counts (always fresh)
    db_tables = await _get_db_table_counts(db)
    view_counts = await _get_view_counts(db)

    # Build response from analysis + live data
    temporal = analysis.get("temporal", {})
    time_span_years = 0
    for key, val in temporal.items():
        if isinstance(val, dict) and "years" in val:
            time_span_years = max(time_span_years, val.get("years", 0))

    sources = _build_sources(analysis)

    result = {
        "overview": {
            "total_files": analysis.get("total_files", 0),
            "total_rows": analysis.get("total_rows", 0),
            "data_sources": len(sources),
            "time_span_years": time_span_years,
        },
        "sources": sources,
        "db_tables": db_tables,
        "materialized_views": view_counts,
        "emiratisation": _build_emiratisation(analysis),
        "geographic_coverage": _build_geographic_coverage(),
        "data_quality": _build_data_quality(analysis),
        "education_pipeline": _build_education_pipeline(analysis),
        "ai_impact_summary": _build_ai_impact_summary(analysis),
        "skills_taxonomy": _build_skills_taxonomy(analysis),
        "cross_insights": analysis.get("cross_insights", []),
        "temporal_coverage": temporal,
    }

    await cache.set(cache_key, result, ttl=CACHE_TTL)
    return result
