"""add_dimensions_facts_evidence_dashboard

Revision ID: 132039ec7832
Revises: 2582726033da
Create Date: 2026-03-11 22:17:25.608669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '132039ec7832'
down_revision: Union[str, None] = '2582726033da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crosswalk_soc_isco',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soc_code', sa.String(length=10), nullable=False),
    sa.Column('soc_title', sa.String(length=300), nullable=True),
    sa.Column('isco_code', sa.String(length=10), nullable=False),
    sa.Column('isco_title', sa.String(length=300), nullable=True),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('soc_code', 'isco_code')
    )
    op.create_table('dim_discipline',
    sa.Column('discipline_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label_en', sa.String(length=200), nullable=False),
    sa.Column('label_ar', sa.String(length=200), nullable=True),
    sa.Column('code_isced', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('discipline_id')
    )
    op.create_index(op.f('ix_dim_discipline_code_isced'), 'dim_discipline', ['code_isced'], unique=False)
    op.create_table('dim_institution',
    sa.Column('institution_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_en', sa.String(length=300), nullable=False),
    sa.Column('name_ar', sa.String(length=300), nullable=True),
    sa.Column('emirate', sa.String(length=50), nullable=True),
    sa.Column('institution_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('institution_id')
    )
    op.create_table('dim_occupation',
    sa.Column('occupation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_isco', sa.String(length=10), nullable=True),
    sa.Column('code_esco', sa.String(length=200), nullable=True),
    sa.Column('code_soc', sa.String(length=10), nullable=True),
    sa.Column('title_en', sa.String(length=300), nullable=False),
    sa.Column('title_ar', sa.String(length=300), nullable=True),
    sa.Column('isco_major_group', sa.String(length=2), nullable=True),
    sa.Column('synonyms', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('occupation_id')
    )
    op.create_index(op.f('ix_dim_occupation_code_isco'), 'dim_occupation', ['code_isco'], unique=False)
    op.create_table('dim_region',
    sa.Column('region_code', sa.String(length=10), nullable=False),
    sa.Column('emirate', sa.String(length=50), nullable=False),
    sa.Column('emirate_ar', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('region_code')
    )
    op.create_table('dim_sector',
    sa.Column('sector_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label_en', sa.String(length=200), nullable=False),
    sa.Column('label_ar', sa.String(length=200), nullable=True),
    sa.Column('code_isic', sa.String(length=10), nullable=True),
    sa.Column('code_naics', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('sector_id')
    )
    op.create_index(op.f('ix_dim_sector_code_isic'), 'dim_sector', ['code_isic'], unique=False)
    op.create_table('dim_skill',
    sa.Column('skill_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uri_esco', sa.String(length=300), nullable=True),
    sa.Column('label_en', sa.String(length=300), nullable=False),
    sa.Column('label_ar', sa.String(length=300), nullable=True),
    sa.Column('skill_type', sa.String(length=20), nullable=True),
    sa.Column('taxonomy', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_table('dim_time',
    sa.Column('time_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month_label', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('time_id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('sdmx_code_lookup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codelist', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('label_en', sa.String(length=200), nullable=False),
    sa.Column('label_ar', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codelist', 'code')
    )
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('dashboards',
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('dashboard_id')
    )
    op.create_table('dataset_registry',
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('minio_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    op.create_table('fact_ai_exposure_occupation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('occupation_id', sa.Integer(), nullable=False),
    sa.Column('exposure_z', sa.Float(), nullable=True),
    sa.Column('exposure_0_100', sa.Float(), nullable=True),
    sa.Column('automation_probability', sa.Float(), nullable=True),
    sa.Column('llm_exposure', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['occupation_id'], ['dim_occupation.occupation_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_exposure_occ', 'fact_ai_exposure_occupation', ['occupation_id'], unique=False)
    op.create_table('fact_course_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.String(length=100), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('catalog_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['dim_skill.skill_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_demand_vacancies_agg',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('region_code', sa.String(length=10), nullable=False),
    sa.Column('occupation_id', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('experience_band', sa.String(length=20), nullable=True),
    sa.Column('demand_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('dataset_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['occupation_id'], ['dim_occupation.occupation_id'], ),
    sa.ForeignKeyConstraint(['region_code'], ['dim_region.region_code'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['dim_sector.sector_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['dim_time.time_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_demand_vac_occupation', 'fact_demand_vacancies_agg', ['occupation_id'], unique=False)
    op.create_index('ix_demand_vac_time_region', 'fact_demand_vacancies_agg', ['time_id', 'region_code'], unique=False)
    op.create_table('fact_forecast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('occupation_id', sa.Integer(), nullable=True),
    sa.Column('region_code', sa.String(length=10), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('forecast_date', sa.String(length=7), nullable=False),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('predicted_demand', sa.Float(), nullable=True),
    sa.Column('predicted_supply', sa.Float(), nullable=True),
    sa.Column('predicted_gap', sa.Float(), nullable=True),
    sa.Column('confidence_lower', sa.Float(), nullable=True),
    sa.Column('confidence_upper', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['occupation_id'], ['dim_occupation.occupation_id'], ),
    sa.ForeignKeyConstraint(['region_code'], ['dim_region.region_code'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['dim_sector.sector_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forecast_occ_region', 'fact_forecast', ['occupation_id', 'region_code'], unique=False)
    op.create_table('fact_occupation_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('occupation_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['occupation_id'], ['dim_occupation.occupation_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['dim_skill.skill_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_occ_skills_occ', 'fact_occupation_skills', ['occupation_id'], unique=False)
    op.create_index('ix_occ_skills_skill', 'fact_occupation_skills', ['skill_id'], unique=False)
    op.create_table('fact_supply_graduates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.Column('region_code', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('nationality', sa.String(length=20), nullable=True),
    sa.Column('expected_graduates_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('dataset_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['dim_discipline.discipline_id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['dim_institution.institution_id'], ),
    sa.ForeignKeyConstraint(['region_code'], ['dim_region.region_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_supply_talent_agg',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('region_code', sa.String(length=10), nullable=False),
    sa.Column('occupation_id', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('nationality', sa.String(length=20), nullable=True),
    sa.Column('age_group', sa.String(length=20), nullable=True),
    sa.Column('experience_band', sa.String(length=20), nullable=True),
    sa.Column('supply_count', sa.Integer(), nullable=False),
    sa.Column('wage_band', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('dataset_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['occupation_id'], ['dim_occupation.occupation_id'], ),
    sa.ForeignKeyConstraint(['region_code'], ['dim_region.region_code'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['dim_sector.sector_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['dim_time.time_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_supply_talent_occupation', 'fact_supply_talent_agg', ['occupation_id'], unique=False)
    op.create_index('ix_supply_talent_time_region', 'fact_supply_talent_agg', ['time_id', 'region_code'], unique=False)
    op.create_table('chat_messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('ix_chat_msg_session', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('dashboard_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.dashboard_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_store',
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('dataset_id', sa.String(length=64), nullable=True),
    sa.Column('query_sql', sa.Text(), nullable=True),
    sa.Column('result_hash', sa.String(length=64), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('citation_label', sa.String(length=200), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_registry.dataset_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index('ix_evidence_trace', 'evidence_store', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evidence_trace', table_name='evidence_store')
    op.drop_table('evidence_store')
    op.drop_table('dashboard_versions')
    op.drop_index('ix_chat_msg_session', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_supply_talent_time_region', table_name='fact_supply_talent_agg')
    op.drop_index('ix_supply_talent_occupation', table_name='fact_supply_talent_agg')
    op.drop_table('fact_supply_talent_agg')
    op.drop_table('fact_supply_graduates')
    op.drop_index('ix_occ_skills_skill', table_name='fact_occupation_skills')
    op.drop_index('ix_occ_skills_occ', table_name='fact_occupation_skills')
    op.drop_table('fact_occupation_skills')
    op.drop_index('ix_forecast_occ_region', table_name='fact_forecast')
    op.drop_table('fact_forecast')
    op.drop_index('ix_demand_vac_time_region', table_name='fact_demand_vacancies_agg')
    op.drop_index('ix_demand_vac_occupation', table_name='fact_demand_vacancies_agg')
    op.drop_table('fact_demand_vacancies_agg')
    op.drop_table('fact_course_skills')
    op.drop_index('ix_ai_exposure_occ', table_name='fact_ai_exposure_occupation')
    op.drop_table('fact_ai_exposure_occupation')
    op.drop_table('dataset_registry')
    op.drop_table('dashboards')
    op.drop_table('chat_sessions')
    op.drop_table('sdmx_code_lookup')
    op.drop_table('dim_time')
    op.drop_table('dim_skill')
    op.drop_index(op.f('ix_dim_sector_code_isic'), table_name='dim_sector')
    op.drop_table('dim_sector')
    op.drop_table('dim_region')
    op.drop_index(op.f('ix_dim_occupation_code_isco'), table_name='dim_occupation')
    op.drop_table('dim_occupation')
    op.drop_table('dim_institution')
    op.drop_index(op.f('ix_dim_discipline_code_isced'), table_name='dim_discipline')
    op.drop_table('dim_discipline')
    op.drop_table('crosswalk_soc_isco')
    # ### end Alembic commands ###
