"""Email report delivery service.

Supports SMTP or SendGrid for sending reports as PDF attachments.
"""
import logging
import smtplib
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from src.config import settings

logger = logging.getLogger(__name__)


async def send_report_email(
    to_email: str,
    subject: str,
    body_text: str,
    pdf_bytes: bytes | None = None,
    pdf_filename: str = "report.pdf",
) -> bool:
    """Send an email with an optional PDF attachment.

    Uses SMTP settings from environment:
    - SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, SMTP_FROM
    """
    smtp_host = getattr(settings, "SMTP_HOST", None)
    smtp_port = int(getattr(settings, "SMTP_PORT", 587))
    smtp_user = getattr(settings, "SMTP_USER", None)
    smtp_pass = getattr(settings, "SMTP_PASSWORD", None)
    smtp_from = getattr(settings, "SMTP_FROM", smtp_user or "noreply@observator.ae")

    if not smtp_host or not smtp_user:
        logger.warning("SMTP not configured — cannot send email")
        return False

    try:
        msg = MIMEMultipart()
        msg["From"] = smtp_from
        msg["To"] = to_email
        msg["Subject"] = subject

        msg.attach(MIMEText(body_text, "html"))

        if pdf_bytes:
            attachment = MIMEApplication(pdf_bytes, _subtype="pdf")
            attachment.add_header("Content-Disposition", "attachment", filename=pdf_filename)
            msg.attach(attachment)

        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            if smtp_port != 25:
                server.starttls()
            if smtp_pass:
                server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_from, [to_email], msg.as_string())

        logger.info(f"Email sent to {to_email}: {subject}")
        return True

    except Exception as e:
        logger.error(f"Failed to send email to {to_email}: {e}")
        return False


async def send_scheduled_report(
    report_type: str,
    to_email: str,
    db=None,
) -> bool:
    """Generate and email a scheduled report."""
    from src.reporting.pdf_generator import generate_pdf

    if db is None:
        logger.error("Database session required for report generation")
        return False

    try:
        pdf_bytes = await generate_pdf(report_type, {}, db)
        title_map = {
            "executive": "Executive Summary",
            "skill_gap": "Skill Gap Analysis",
            "emiratisation": "Emiratisation Progress",
            "ai_risk": "AI Risk Assessment",
        }
        title = title_map.get(report_type, "Report")
        filename = f"observator_{report_type}_report.pdf"

        body = f"""
        <html>
        <body style="font-family: Inter, sans-serif; color: #1a1a2e;">
            <h2 style="color: #003366;">Observator Report: {title}</h2>
            <p>Your scheduled {title} report is attached.</p>
            <p style="color: #666; font-size: 12px;">
                Generated by Observator — UAE Labour Market Intelligence Platform<br>
                This is an automated report. Do not reply to this email.
            </p>
        </body>
        </html>
        """

        return await send_report_email(
            to_email=to_email,
            subject=f"Observator: {title} Report",
            body_text=body,
            pdf_bytes=pdf_bytes,
            pdf_filename=filename,
        )

    except Exception as e:
        logger.error(f"Scheduled report failed for {report_type}: {e}")
        return False
