// Research Brief — editorial content panel.
// Text content is static/curated. Will be generated by ReportGeneratorAgent in Phase 2.
import { useState } from 'react';
import { motion } from 'framer-motion';
import { useLanguage } from '@/contexts/LanguageContext';
import { BookOpen, ChevronDown, ChevronRight, FileText, Database, Calendar, ExternalLink, Copy, Download, X, PanelRightClose, PanelRightOpen } from 'lucide-react';

interface Citation {
  id: string;
  source: string;
  version: string;
  refreshedAt: string;
  excerpt?: string;
}

interface ResearchBriefProps {
  collapsed?: boolean;
  onToggle?: () => void;
}

const citations: Citation[] = [
  { id: 'ds_001', source: 'MOHRE WPS Register', version: 'v3.1', refreshedAt: '2h ago', excerpt: 'Labour force participation data by emirate and sector' },
  { id: 'ds_002', source: 'FCSC Labour Force Survey Q4', version: 'v2.0', refreshedAt: '4h ago', excerpt: 'Quarterly labour market indicators' },
  { id: 'ds_003', source: 'ESCO Occupations Taxonomy', version: 'v4.0', refreshedAt: '2 months ago', excerpt: 'Standardized occupation and skill classifications' },
  { id: 'ds_004', source: 'Bayt.com Job Listings', version: 'v1.0', refreshedAt: '1h ago', excerpt: 'Current vacancy demand signals' },
];

const ResearchBrief = ({ collapsed = false, onToggle }: ResearchBriefProps) => {
  const { t } = useLanguage();
  const [expandedSections, setExpandedSections] = useState<Set<string>>(new Set(['findings', 'methodology']));

  const toggleSection = (section: string) => {
    setExpandedSections(prev => {
      const next = new Set(prev);
      if (next.has(section)) next.delete(section);
      else next.add(section);
      return next;
    });
  };

  if (collapsed) {
    return (
      <button
        onClick={onToggle}
        className="fixed right-4 top-16 z-30 flex items-center gap-1.5 px-3 py-2 rounded-lg bg-card border border-border-light shadow-card text-xs text-text-secondary hover:bg-surface-hover transition-colors"
      >
        <PanelRightOpen className="w-4 h-4" />
        {t('فتح التقرير', 'Open Brief')}
      </button>
    );
  }

  const Section = ({ id, title, children }: { id: string; title: string; children: React.ReactNode }) => {
    const open = expandedSections.has(id);
    return (
      <div className="border-b border-border-light last:border-0">
        <button onClick={() => toggleSection(id)} className="flex items-center gap-2 w-full px-4 py-2.5 text-left hover:bg-surface-hover transition-colors">
          {open ? <ChevronDown className="w-3.5 h-3.5 text-text-muted shrink-0" /> : <ChevronRight className="w-3.5 h-3.5 text-text-muted shrink-0" />}
          <span className="text-xs font-semibold text-primary">{title}</span>
        </button>
        {open && <div className="px-4 pb-3 text-xs text-text-secondary leading-relaxed">{children}</div>}
      </div>
    );
  };

  return (
    <motion.aside
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      className="bg-card border-l border-border-light h-full flex flex-col overflow-hidden"
    >
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-border-light shrink-0">
        <div className="flex items-center gap-2">
          <BookOpen className="w-4 h-4 text-navy" />
          <h3 className="text-sm font-semibold text-primary">{t('ملخص بحثي', 'Research Brief')}</h3>
        </div>
        <div className="flex items-center gap-1">
          <button className="p-1.5 rounded-md hover:bg-surface-tertiary transition-colors" title="Copy">
            <Copy className="w-3.5 h-3.5 text-text-muted" />
          </button>
          <button className="p-1.5 rounded-md hover:bg-surface-tertiary transition-colors" title="Export PDF">
            <Download className="w-3.5 h-3.5 text-text-muted" />
          </button>
          <button onClick={onToggle} className="p-1.5 rounded-md hover:bg-surface-tertiary transition-colors" title="Close">
            <PanelRightClose className="w-3.5 h-3.5 text-text-muted" />
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto">
        <Section id="introduction" title={t('المقدمة', 'Introduction')}>
          <p>{t(
            'يقدم هذا التقرير تحليلاً شاملاً لفجوات المهارات في سوق العمل الإماراتي بناءً على أحدث البيانات المتاحة من مصادر حكومية وخاصة.',
            'This brief presents a comprehensive analysis of skill gaps in the UAE labour market based on the latest available data from government and private sources.'
          )}</p>
          <p className="mt-2">{t(
            'يغطي التحليل 7 إمارات و 6 قطاعات رئيسية مع التركيز على 23 مهنة تعاني من نقص حاد.',
            'The analysis covers 7 emirates and 6 major sectors, focusing on 23 occupations experiencing critical shortages.'
          )}</p>
        </Section>

        <Section id="methodology" title={t('المنهجية', 'Methodology')}>
          <p>{t(
            'يتم حساب مؤشر فجوة المهارات (SGI) باستخدام:',
            'The Skill Gap Index (SGI) is computed using:'
          )}</p>
          <ul className="mt-1.5 space-y-1 ms-3">
            <li className="flex gap-1.5"><span className="text-gold">•</span>{t('بيانات الطلب من الوظائف الشاغرة المجمعة', 'Demand data from aggregated vacancy postings')}</li>
            <li className="flex gap-1.5"><span className="text-gold">•</span>{t('بيانات العرض من سجلات القوى العاملة', 'Supply data from workforce registers')}</li>
            <li className="flex gap-1.5"><span className="text-gold">•</span>{t('تصنيف المهن وفقاً لـ ISCO-08 / ESCO', 'Occupation classification via ISCO-08 / ESCO')}</li>
            <li className="flex gap-1.5"><span className="text-gold">•</span>{t('حد أدنى للمجموعة: N ≥ 10', 'Minimum cohort threshold: N ≥ 10')}</li>
          </ul>
          <p className="mt-2 text-[11px] text-text-muted">SGI = (Demand − Supply) / Demand × 100</p>
        </Section>

        <Section id="findings" title={t('النتائج الرئيسية', 'Key Findings')}>
          <div className="space-y-2">
            <div className="p-2 rounded-lg bg-sgi-critical/5 border border-sgi-critical/10">
              <p className="font-medium text-sgi-critical">{t('نقص حاد في 5 مهن تقنية', 'Critical shortage in 5 technology occupations')}</p>
              <p className="mt-0.5 text-text-muted">{t('مهندس الذكاء الاصطناعي يتصدر بنسبة 43%', 'AI Engineers lead at +43% SGI')} <span className="text-[10px] text-navy cursor-pointer hover:underline">[ds_001, ds_004]</span></p>
            </div>
            <div className="p-2 rounded-lg bg-sgi-shortage/5 border border-sgi-shortage/10">
              <p className="font-medium text-sgi-shortage">{t('أبوظبي ودبي أعلى فجوة', 'Abu Dhabi and Dubai show highest gaps')}</p>
              <p className="mt-0.5 text-text-muted">{t('مؤشر فجوة المهارات 22% و 19% على التوالي', 'SGI at 22% and 19% respectively')} <span className="text-[10px] text-navy cursor-pointer hover:underline">[ds_001, ds_002]</span></p>
            </div>
            <div className="p-2 rounded-lg bg-sgi-balanced/5 border border-sgi-balanced/10">
              <p className="font-medium text-sgi-balanced">{t('تحسن معدل التوطين', 'Emiratisation rate improving')}</p>
              <p className="mt-0.5 text-text-muted">{t('ارتفع بنسبة 0.6% خلال الربع الأخير', 'Up 0.6% over last quarter')} <span className="text-[10px] text-navy cursor-pointer hover:underline">[ds_002]</span></p>
            </div>
          </div>
        </Section>

        <Section id="forecasts" title={t('التوقعات', 'Forecasts & Assumptions')}>
          <p>{t(
            'بناءً على الاتجاهات الحالية (نموذج ETS/ARIMA):',
            'Based on current trends (ETS/ARIMA model):'
          )}</p>
          <ul className="mt-1.5 space-y-1 ms-3">
            <li className="flex gap-1.5"><span className="text-gold">•</span>{t('الطلب على مهن التقنية يرتفع 12% سنوياً', 'Technology occupation demand growing 12% YoY')}</li>
            <li className="flex gap-1.5"><span className="text-gold">•</span>{t('تحتاج الإمارات ~2000 مقعد تدريبي إضافي للذكاء الاصطناعي', 'UAE needs ~2,000 additional AI training seats')}</li>
            <li className="flex gap-1.5"><span className="text-gold">•</span>{t('التوازن المتوقع في 14 شهراً مع التدخل', 'Balance expected in 14 months with intervention')}</li>
          </ul>
          <p className="mt-2 text-[11px] text-text-muted italic">{t('الافتراض: استمرار معدلات النمو الحالية', 'Assumption: Current growth rates continue')}</p>
        </Section>

        <Section id="recommendations" title={t('التوصيات', 'Recommendations')}>
          <div className="space-y-2">
            <div className="p-2 rounded-lg bg-navy/5 border border-navy/10">
              <p className="font-medium text-navy">{t('زيادة مقاعد التدريب التقني', 'Scale up technical training seats')}</p>
              <p className="mt-0.5 text-text-muted">{t('إضافة 2,000+ مقعد في الذكاء الاصطناعي والأمن السيبراني بحلول 2027', 'Add 2,000+ seats in AI & Cybersecurity by 2027')} <span className="text-[10px] text-navy cursor-pointer hover:underline">[ds_001, ds_004]</span></p>
            </div>
            <div className="p-2 rounded-lg bg-navy/5 border border-navy/10">
              <p className="font-medium text-navy">{t('تعزيز برامج التوطين في التقنية', 'Strengthen Emiratisation in tech')}</p>
              <p className="mt-0.5 text-text-muted">{t('استهداف 8% توطين في قطاع التقنية بحلول 2028', 'Target 8% Emiratisation in tech sector by 2028')} <span className="text-[10px] text-navy cursor-pointer hover:underline">[ds_002]</span></p>
            </div>
            <div className="p-2 rounded-lg bg-navy/5 border border-navy/10">
              <p className="font-medium text-navy">{t('مواءمة مناهج الجامعات', 'Align university curricula')}</p>
              <p className="mt-0.5 text-text-muted">{t('سد فجوة 85% في التعلم الآلي عبر برامج مشتركة مع الصناعة', 'Close 85% ML gap via industry-academia joint programs')} <span className="text-[10px] text-navy cursor-pointer hover:underline">[ds_001, ds_003]</span></p>
            </div>
          </div>
        </Section>

        <Section id="limitations" title={t('القيود', 'Limitations & Future Work')}>
          <ul className="space-y-1 ms-3">
            <li className="flex gap-1.5"><span className="text-text-muted">•</span>{t('بيانات العرض تعتمد على لقطة واحدة', 'Supply data based on single snapshot')}</li>
            <li className="flex gap-1.5"><span className="text-text-muted">•</span>{t('بيانات Bayt.com غير محققة بالكامل', 'Bayt.com data not fully validated')}</li>
            <li className="flex gap-1.5"><span className="text-text-muted">•</span>{t('لا يتضمن القطاع غير الرسمي', 'Informal sector not included')}</li>
          </ul>
        </Section>

        {/* Data Sources / References */}
        <div className="border-t border-border-light">
          <div className="px-4 py-2.5">
            <span className="text-xs font-semibold text-primary flex items-center gap-1.5">
              <Database className="w-3.5 h-3.5" />
              {t('المراجع ومصادر البيانات', 'References & Data Sources')}
            </span>
          </div>
          <div className="px-4 pb-3 space-y-2">
            {citations.map(c => (
              <div key={c.id} className="flex items-start gap-2 p-2 rounded-lg bg-surface-tertiary/50 hover:bg-surface-tertiary transition-colors">
                <FileText className="w-3.5 h-3.5 text-navy mt-0.5 shrink-0" />
                <div className="min-w-0">
                  <div className="flex items-center gap-1.5">
                    <span className="text-[11px] font-medium text-primary truncate">{c.source}</span>
                    <span className="text-[10px] text-text-muted shrink-0">{c.version}</span>
                  </div>
                  {c.excerpt && <p className="text-[10px] text-text-muted mt-0.5 line-clamp-1">{c.excerpt}</p>}
                  <div className="flex items-center gap-2 mt-1">
                    <span className="text-[10px] text-text-muted flex items-center gap-0.5"><Calendar className="w-2.5 h-2.5" />{c.refreshedAt}</span>
                    <span className="text-[10px] text-navy font-mono">[{c.id}]</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </motion.aside>
  );
};

export default ResearchBrief;
